### PR TITLE
Add event

### PR DESCRIPTION
**Pull request by Rjbeckwith55**
Added other fields to addEvent and handle camera image

### CODE REVIEW

**Review by adityapstar — COMMENTED** [review]
I noticed you had a large chunk of duplicated code, could you refactor that?

**Review by KrastanD — APPROVED** [review]
Good work, I like the tests.

**Comment by Rjbeckwith55** [comment]
> I noticed you had a large chunk of duplicated code, could you refactor that?

I added the if statement at the top to fix the duplicated code.

**Review by adityapstar — APPROVED** [review]
Ty

**Pull request merged**
